remote:
  endpoint:
    push-notification-service: komoot-challenge-dev.us-east-1.elasticbeanstalk.com/api/receive
    sns-topic: arn:aws:sns:us-east-1:778662507906:challenge-backend-signups
    aws-region: us-east-1
server:
  protocol: http
  host: komoot-challenge-dev.us-east-1.elasticbeanstalk.com
  port: 8090
  mail: fabian.finke@gmx.de
logging:
  level:
    root: INFO
    org.springframework.web: TRACE
