remote:
  endpoint:
    push-notification-service: https://notification-backend-challenge.main.komoot.net/
    sns-topic: arn:aws:sns:eu-west-1:963797398573:challenge-backend-signups
    aws-region: eu-west-1
server:
  protocol: http
  host: komoot-challenge-dev.us-east-1.elasticbeanstalk.com
  port: 8090
  mail: fabian.finke@gmx.de
